### ISSUE TITLE
如何使用?

### ISSUE THREAD

**Issue by Andy766** [kazhafeizhale/super-command#2]
大佬您好 我是AHK 菜鸟想了解一下这个代码管理软件 感觉非常好用 但是能力有限 无法使用
可以远程教学一下如何在Windows 配置和使用supper_command-master这个项目吗?

**Comment by sxzxs** [comment]
点击链接加入群聊【ahk代码片段管理软件】：https://jq.qq.com/?_wv=1027&k=sxkummKG
