### ISSUE TITLE
修改“发送文件”命令的快捷键无效

### ISSUE THREAD

**Issue by vanadis91** [kazhafeizhale/super-command#4]
修改“发送文件”命令的快捷键无效
![image](https://user-images.githubusercontent.com/54221691/186100870-317b5c14-44a8-4e54-984e-c018f076802e.png)
![image](https://user-images.githubusercontent.com/54221691/186101001-fe20187e-285c-44e7-aab8-04c1a7280611.png)

**Comment by sxzxs** [comment]
1、通过set.ahk或者set.exe修改
2、或者直接修改config/settings.json
